### PR TITLE
Cloud

### PR DESCRIPTION
**Pull request by cloud007bond**
This pull request introduces a comprehensive Hello-Microverse-Project, focusing on enhanced linters and error handling. The changes encompass both the linter, index.html, style.css, linters, allowing the code to run successfully.

### CODE REVIEW

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @cloud007bond      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done e well so far in this project,  However, there's one adjustment you need to make to move to the next project. 💯



## Highlights   
- Good use of GitHub features ✔️  
  
# Required Changes  🌵 

- [x] You made some impressive implementations which I must say is a job well done. However, there are a few  I suggest   you make In line with the requirements 

- Firstly, always make your branch name very descriptive relating to the project. `cloud` does not in any way relate to the changes. Try namings like `HTML-CSS_linters_setup` or `Created_html_css_and_linters_setup`. This makes it a whole lot better because you'll be working with teams in the future with which you need clarity to collaborate 👍 

- [ ] Kindly make your Pull request summary very descriptive to describe the changes in this branch. You can follow this [Link](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) to see a detailed guide on how to make a very proffesinal and descriptive pull request. Yours looks empty for now.
- Kindly follow the red arrow i pointed to edit it using the link i provided above

## Your PR that needs changes:
image


- [ ] You missed two important linter files which were meant to run to have the workflow work properly. These files help you stick to best practices and make you a better developer 👍 
## Missing linter  files:
image

- [ ] Nice work adding the [README](https://github.com/microverseinc/readme-template) file. Please personalize it to this project in every section. 
- All sections with the `>` should be deleted

## Expected READE header:
image



_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES 🟡

Hi @cloud007bond 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

AlmostThereGIF


 ## Required Changes ♻️
_Check the comments under the review._

- [ ] Excellent job building your README file 🚀. However, please kindly ensure to use the README provided by Microverse to document your project as requested by the previous reviewer. 🤓 You can get the [README template here](https://github.com/microverseinc/readme-template).
     >Hint - remember to add all the project's specific information to the README file and delete all the comments inside of it. 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ademibowale — CHANGES_REQUESTED** [review]
## STATUS: Changes Required :recycle:

### Hi @cloud007bond  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._

Excellent job building your README file 🚀. However, please kindly follow the guildlines and ensure to  use the README provided by Microverse to document your project as requested by the previous reviewer. 🤓 You can get the [README template here](https://github.com/microverseinc/readme-template).
`Hint - remember to add all the project's specific information to the README file and delete all the comments inside of it.`
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Shedrack-Sunday — CHANGES_REQUESTED** [review]
Hello @cloud007bond      👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done e well so far in this project,  However, there's one adjustment you need to make to move to the next project. 💯



## Highlights   
- Good use of GitHub features ✔️  
  
# Required Changes  🌵  

- [ ] Just as I said earlier, please follow the  [README](https://github.com/microverseinc/readme-template) file link to update your README. Please personalize it to this project in every section. 
- All sections with the `>` should be deleted

## Expected READE header:
image

## Your Header:
image



_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES 🟡

Hi @cloud007bond 👋🏽, 

Great work on making the changes requested by a previous reviewer 👌
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

AlmostThereGIF


 ## Required Changes ♻️
- [ ] Great work meeting all the other requirements for this project 💯. However, please kindly ensure to document your project using the Microverse [README template](https://github.com/microverseinc/readme-template), currently, you are not using it and this is the only thing holding you from succeeding in this Milestone, remember that sending your project again without implementing the changes in the README file will cause the same outcome: "Changes Required". 🤓

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
